apiVersion: v1
kind: Pod
metadata: 
  name: mytodoapp
  labels:
    app: mytodoapp
spec: 
  containers: 
    - name: todo
      image: aamantamboli/todoapp
      ports:  
        - containerPort: 80
          protocol: TCP 