apiVersion: v1
kind: Pod
metadata: 
  name: mystudentapp
  labels:
    app: mystudentapp
spec: 
  containers: 
    - name: student
      image: aamantamboli/student
      ports:
        - containerPort: 8080
          protocol: TCP