apiVersion: v1
kind: Service
metadata:
  name: puppyapp
spec:
  type: ClusterIP
  selector:
    app: puppyapp
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
