apiVersion: v1
kind: Service
metadata:
  name: trafficapp
spec:
  type: ClusterIP
  selector:
    app: trafficapp
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
