apiVersion: v1
kind: Service
metadata:
  name: numberapp
spec:
  type: ClusterIP
  selector:
    app: numberapp
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
