apiVersion: v1
kind: Service
metadata:
  name: seasonapp
spec:
  type: ClusterIP
  selector:
    app: seasonapp
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
