apiVersion: apps/v1
kind: ReplicaSet
metadata: 
      name: webreplica3
      labels: 
          app: webreplica3
spec: 
  replicas: 2
  template: 
        metadata: 
            name: webreplica3
            labels:
              app: webreplica3
        spec: 
          containers: 
            - name: todo
              image: aamantamboli/todoapp
              resources: 
                requests:
                  cpu: "50m"
                  memory: "90Mi" 
              ports:  
                - containerPort: 80
                  protocol: TCP 
  selector:
    matchExpressions:  
        - {key: app, operator: Exists}